# Generated by Django 3.2.5 on 2021-07-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=90)),
                ('lname', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('profile', models.ImageField(upload_to='pics')),
                ('file', models.FileField(upload_to='')),
                ('exp', models.IntegerField()),
                ('dob', models.DateTimeField()),
            ],
        ),
    ]
